spring:
  application:
    name: eureka-client
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    # 拉取注册信息的频率
    registry-fetch-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 10 # 默认为300秒，这里为了验证改为10秒

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Feign添加Gzip压缩
feign:
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true
  httpclient:
    enabled: false
  # 开启okhttp  后期可自定义config自己扩展okhttp的更多配置
  okhttp:
    enabled: true
  # 全局配置
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

#        retryer: # 重试 Class<Retryer>
#        errorDecoder: # 错误解码器 Class<ErrorDecoder>
#        requestInterceptors: # ** List<Class<RequestInterceptor>>
#        decode404: false
#        decoder: # 解码器 Class<Decoder>
#        encoder: # 编码器 Class<Encoder>
#        contract: # contract配置 Class<Contract>

logging:
  level:
    ltd.beihu.core.cloud.eureka.client.service.FeignTestService: debug