

# 当前服务名
spring:
  application:
    name: eureka-server
server:
  port: 8763

# 实例名称
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    # 检索服务
    fetch-registry: true
    # 是否注册自己
    register-with-eureka: true
    service-url:
      # 默认域
#      defaultZone: http://localhost:8761/eureka/ # one eureka server
#      defaultZone: http://localhost:8762/eureka/ # two eureka server
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/ # three eureka server
  server:
    # 自我保护
    enable-self-preservation: false
    # 禁止：使用 readOnlyCacheMap
    use-read-only-response-cache: false
    # readWriteCacheMap的过期时间
    response-cache-auto-expiration-in-seconds: 60
    wait-time-in-ms-when-sync-empty: 0